
author:
    - name: Seyi Adepoju
      email: adepojus@vcu.edu

date: 04-26-2025

format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
